FROM ubuntu:disco-20191127
ARG DEBIAN_FRONTEND=noninteractive
USER root
COPY ./tex_root.sh ./tmp/tex_root.sh
RUN ./tmp/tex_root.sh
RUN rm ./tmp/tex_root.sh
RUN apt-get -qq purge && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen
ENV \
    SHELL=/bin/bash \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
