# load in your custom aliases
[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.bash_completion ] && source ~/.bash_completion

# SSH
eval $(ssh-agent -s) >/dev/null 2>&1
# separate keys for git@[mp|mm].github.com:[username]/[repo]
[ -f ~/.ssh/id_rsa_mm ] && ssh-add ~/.ssh/id_rsa_mm >/dev/null 2>&1
[ -f ~/.ssh/id_rsa_mp ] && ssh-add ~/.ssh/id_rsa_mp >/dev/null 2>&1


# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# docker machine env
eval $(docker-machine env default) > /dev/null 2>&1
