execute pathogen#infect()

set rtp+=/usr/local/opt/fzf
set nu
syntax on 
set tabstop=4
set shiftwidth=4
set expandtab
"<bar> separates commands. <CR> is carriage return - equivalent of pressing enter"
map tt :tabe 
map ! :! 
map FF :FZF <CR>
"load in bash aliases"
let $BASH_ENV = "~/.bash_aliases"

"spellcheck!"
set spelllang=en_us
set spellfile=$HOME/.vim/spell/en.utf-8.add
set spell

